menu:

- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'talks', url: '/talks'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

talks:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'History and Philosophy of Science I'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'Google Scholar', link: 'https://scholar.google.com/citations?user=tDSs_kcAAAAJ&hl=en'}
- {icon: 'Academia', link: 'https://uni-duesseldorf.academia.edu/MatíasOstaVélez'}
- {icon: 'Researchgate', link: 'https://www.researchgate.net/profile/Matias-Osta-Velez?ev=hdr_xprf'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
