menu:

- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'talks', url: '/talks'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

talks:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'History and Philosophy of Science II', url: 'https://fhce.edu.uy/wp-content/uploads/2025/07/HISTORIA-Y-FILOSOFIA-DE-LA-CIENCIA-II.pdf'} 
- {name: 'Philosophy of the Social Sciences', url: 'https://fhce.edu.uy/wp-content/uploads/2024/07/Filosofi%CC%81a-de-las-ciencias-sociales.pdf'}
- {name: 'Formal methods in Philosophy of Science', url: 'https://fhce.edu.uy/wp-content/uploads/2023/03/TOPICO-HISTORIA-Y-FILOSOFIA-DE-LA-CIENCIA.pdf'}

social:
- {icon: 'Google Scholar', link: 'https://scholar.google.com/citations?user=tDSs_kcAAAAJ&hl=en'}
- {icon: 'Academia', link: 'https://uni-duesseldorf.academia.edu/Mat%C3%ADasOstaV%C3%A9lez'}
- {icon: 'Researchgate', link: 'https://www.researchgate.net/profile/Matias-Osta-Velez?ev=hdr_xprf'}

contacts:
- {name: 'Matías Osta Vélez', department: 'Instituto de Filosofía', institution: 'Facultad de Humanidades y Ciencias de la Educación (Udelar)', institution_address: 'Av. Uruguay 1695, 11200 Montevideo, Uruguay', phone: '(00598) 2409 1104', email: 'matiasosta [at] gmail.com', image: 'assets/img/contact.jpg'}
